CREATE TABLE `registrations` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`title` varchar(50) NOT NULL,
	`first_name` varchar(255) NOT NULL,
	`last_name` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`affiliation` varchar(255) NOT NULL,
	`country` varchar(100) NOT NULL,
	`is_local` boolean NOT NULL DEFAULT false,
	`registration_category` varchar(50) NOT NULL,
	`author_type` varchar(50) NOT NULL,
	`is_ieee_member` boolean NOT NULL DEFAULT false,
	`is_student` boolean NOT NULL DEFAULT false,
	`ieee_member_number` varchar(100),
	`paper_ids` varchar(255),
	`extra_banquet_tickets` int NOT NULL DEFAULT 0,
	`amount` decimal(10,2) NOT NULL,
	`currency` varchar(10) NOT NULL,
	`ieee_proof_path` varchar(500),
	`student_proof_path` varchar(500),
	`payment_status` varchar(50) NOT NULL DEFAULT 'pending',
	`session_id` varchar(255),
	`invoice_id` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `registrations_id` PRIMARY KEY(`id`)
);
